src/DejaVuBundle/Entity/SeriesRepository.php
<?php

namespace DejaVuBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository
{
    public function getStats() { //todo verif
        $request = '
        SELECT TM.name,
        COUNT(SR.id) as total,
        TS.total_se,' . '
        T.total_ep
        FROM series SR
            LEFT JOIN type TM
                ON TM.id = SR.type_id
            LEFT JOIN (
                SELECT
                  SE.id,
                  count(S.id) as total_se
                FROM seasons S
                    LEFT JOIN series SE
                        ON S.serie_id = SE.id
                    LEFT JOIN type TY
                        ON TY.id = SE.type_id
                GROUP BY TY.id
            ) TS
                ON TS.id = SR.id
            LEFT JOIN (
                SELECT
                  SE.id,
                  count(E.id) as total_ep
                FROM episodes E
                    LEFT JOIN seasons S
                        ON E.season_id = S.id
                    LEFT JOIN series SE
                        ON S.serie_id = SE.id
                    LEFT JOIN type TY
                        ON TY.id = SE.type_id
                GROUP BY TY.id
            ) T
                ON T.id = SR.id
        GROUP BY TM.id;
        ';

        return $this->getEntityManager()->getConnection()->executeQuery($request)->fetchAll();
    }

    public function getAllUserSeries($id){
        $request = '' . '
        SELECT
            SE.id,
            SE.title,
            SE.alternativ_title,
            SE.is_finish,
            SE.authors,
            SE.url_img,
            KD.kind as kind,
            LC.name,
            TM.name,
            COALESCE(UHE.nb_seen,0) AS nb_seen,
            COALESCE(SA.nb_saisons,0) AS nb_saisons,
            COALESCE(EP.nb_episodes,0) AS nb_episodes
        FROM series SE
            LEFT JOIN (
                SELECT serie_id,
                COUNT(*) AS nb_saisons
                FROM seasons
                GROUP BY serie_id
            ) SA
                ON SE.id = SA.serie_id
            LEFT JOIN licensee LC
                ON SE.licensee_id = LC.id
            LEFT JOIN type TM
                ON TM.id = SE.type_id
            LEFT JOIN (
                    SELECT
                        S.serie_id,
                        E.id,
                        COUNT(*) AS nb_episodes
                    FROM
                        seasons S
                            INNER JOIN episodes E
                                ON S.id = E.season_id
                    GROUP BY S.serie_id
                ) EP
                ON SE.id = EP.serie_id
            LEFT JOIN (
                SELECT
                    S.serie_id,
                    E.id,
                    COUNT(*) AS nb_seen
                FROM seasons S
                    INNER JOIN episodes E
                        ON S.id = E.season_id
                    INNER JOIN series SR
                        ON S.serie_id = SR.id
                    INNER JOIN (
                        SELECT * FROM users_has_episodes WHERE user_id = ?
                    ) UE
                        ON UE.episode_id = E.id
                GROUP BY S.serie_id
            ) UHE
                ON UHE.serie_id = EP.serie_id
            LEFT JOIN (
                SELECT
                    SHT.serie_id,
                    GROUP_CONCAT(TP.name) as kind
                FROM series_has_kind SHT
                    INNER JOIN type TP
                        ON TP.id = SHT.kind_id
                GROUP BY SHT.serie_id ASC
            ) KD
                ON KD.serie_id = SE.id
        ORDER BY title ASC;
        ';

        $a = $this->getEntityManager()->getConnection()->prepare($request);
        $a->execute(array($id));
        return $a->fetchAll();
    }

    public function getUserSerie($id,$user_id){
        $request = '
        SELECT' . '
            SE.serie_id,
            SE.title,
            SE.alternativ_title,
            SE.description,
            SE.is_finish,
            SE.authors,
            SE.url_img,
            SE.is_licensed,
            TM.name,
            COALESCE(UHE.nb_seen,0) AS nb_seen,
            COALESCE(SA.nb_saisons,0) AS nb_saisons,
            COALESCE(EP.nb_episodes,0) AS nb_episodes
        FROM
            series SE
                LEFT JOIN (
                    SELECT serie_id,
                    COUNT(*) AS nb_saisons
                    FROM seasons
                    GROUP BY serie_id
                ) SA
                    ON SE.serie_id = SA.serie_id
                LEFT JOIN type_media TM
                    ON TM.type_media_id = SE.type_media_id
                LEFT JOIN (
                        SELECT
                            S.serie_id,
                            E.episode_id,
                            COUNT(*) AS nb_episodes
                        FROM
                            seasons S
                                INNER JOIN episodes E
                                    ON S.season_id = E.season_id
                        GROUP BY S.serie_id
                    ) EP
                    ON SE.serie_id = EP.serie_id
                LEFT JOIN (
                    SELECT UE.episode_id,
                    COUNT(*) AS nb_seen
                    FROM users_has_episodes UE
                        INNER JOIN episodes E
                            ON UE.episode_id = E.episode_id
                        INNER JOIN seasons S
                            ON E.season_id = S.season_id
                    WHERE S.serie_id = ?
                    AND UE.user_id = ?
                ) UHE
                    ON UHE.episode_id = EP.episode_id
            WHERE SE.`serie_id` = ?
            ORDER BY `serie_id` DESC;
        ';
        $a = $this->getEntityManager()->getConnection()->prepare($request);
        $a->execute(array($id,$user_id,$id));
        return $a->fetchAll();
    }

    public function getAllSeries(){
        $request = '' . '
        SELECT
            SE.serie_id,
            SE.title,
            SE.alternativ_title,
            SE.authors,
            SE.url_img,
            SE.is_licensed,
            SE.is_finish,
            KD.kind as kind,
            TM.name,
            COALESCE(SA.nb_saisons,0) AS nb_saisons,
            COALESCE(EP.nb_episodes,0) AS nb_episodes
        FROM series SE
            LEFT JOIN (
                SELECT
                    serie_id,
                    COUNT(*) AS nb_saisons
                FROM seasons
                GROUP BY serie_id
            ) SA
                ON SE.serie_id = SA.serie_id
            LEFT JOIN type_media TM
                ON TM.type_media_id = SE.type_media_id
            LEFT JOIN (
                SELECT
                    S.serie_id,
                    COUNT(*) AS nb_episodes
                FROM
                    seasons S
                        INNER JOIN episodes E
                            ON S.season_id = E.season_id
                GROUP BY S.serie_id
            ) EP
                ON SE.serie_id = EP.serie_id
            LEFT JOIN (
                SELECT
                    SHT.serie_id,
                    GROUP_CONCAT(TP.name) as kind
                FROM series_has_type SHT
                    INNER JOIN type TP
                        ON TP.type_id = SHT.type_id
                GROUP BY SHT.serie_id ASC
            ) KD
                ON KD.serie_id = SE.serie_id
        ORDER BY title ASC;
        ';
        return $this->getEntityManager()->getConnection()->executeQuery($request)->fetchAll();
    }

    public function getSerie($id){
        $request = '
        SELECT' . '
            SE.serie_id,
            SE.title,
            SE.alternativ_title,
            SE.authors,
            SE.url_img,
            SE.is_licensed,
            SE.is_finish,
            SE.description,
            KD.kind as kind,
            TM.name,
            COALESCE(SA.nb_saisons,0) AS nb_saisons,
            COALESCE(EP.nb_episodes,0) AS nb_episodes
        FROM series SE
            LEFT JOIN (
                SELECT
                    serie_id,
                    COUNT(*) AS nb_saisons
                FROM seasons
                GROUP BY serie_id
            ) SA
                ON SE.serie_id = SA.serie_id
            LEFT JOIN type_media TM
                ON TM.type_media_id = SE.type_media_id
            LEFT JOIN (
                SELECT
                    S.serie_id,
                    COUNT(*) AS nb_episodes
                FROM
                    seasons S
                        INNER JOIN episodes E
                            ON S.season_id = E.season_id
                GROUP BY S.serie_id
            ) EP
                ON SE.serie_id = EP.serie_id
            LEFT JOIN (
                SELECT
                    SHT.serie_id,
                    GROUP_CONCAT(TP.name) as kind
                FROM series_has_type SHT
                    INNER JOIN type TP
                        ON TP.type_id = SHT.type_id
                GROUP BY SHT.serie_id ASC
            ) KD
                ON KD.serie_id = SE.serie_id
        WHERE SE.serie_id = ?
        ORDER BY title ASC;
        ';
        $a = $this->getEntityManager()->getConnection()->prepare($request);
        $a->execute(array($id));
        return $a->fetch();
    }

    public function getAllSeriesAdmin(){
        $request = '' . '
        SELECT
            SE.id,
            SE.title,
            TM.name,
            COALESCE(SA.nb_saisons,0) AS nb_saisons,
            COALESCE(EP.nb_episodes,0) AS nb_episodes
        FROM series SE
            LEFT JOIN (
                SELECT
                    id,
                    COUNT(*) AS nb_saisons
                FROM seasons
                GROUP BY id
            ) SA
                ON SE.id = SA.id

src/DejaVuBundle/Controller/DefaultController.php
<?php

namespace DejaVuBundle\Controller;

use DejaVuBundle\Entity\BannedIp;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;


class DefaultController extends Controller
{
    /*
     * Route nomdusite.fr/
     */
    public function indexAction()
    {
        return $this->render('DejaVuBundle:Default:news.html.twig');
    } // GOOD

    /*
     * Pas de route mais génère le menu via la session
     */
    public function menuAction(Request $request)
    {
        $session    = $request->getSession();
        $bdd        = $this->getDoctrine()->getManager();

        if(!$bdd->getRepository('DejaVuBundle:BannedIp')->findOneBy(array('ip' => $request->getClientIp()))) {
            $ip = new BannedIp();
            $ip->setIp($request->getClientIp());
            $bdd->persist($ip);
            $bdd->flush();
        }
        if ($session->get('user')['id']) {

            $get_user = $this->getDoctrine()
                ->getManager()
                ->getRepository('DejaVuBundle:Users')
                ->find($session->get('user')['id']);


            $session->set('user', array(
                'id' => $get_user->getId(),
                'pseudo' => $get_user->getPseudo(),
                'registrationDate' => $get_user->getRegistrationDate(),
                'email' => $get_user->getEmail(),
                'title' => array(
                    'id' => $get_user->getTitle()->getId(),
                    'name' => $get_user->getTitle()->getName(),
                ),
            ));

            $ip = $bdd->getRepository('DejaVuBundle:BannedIp')->findOneBy(array('ip' => $request->getClientIp()));
            $get_user->setIp($ip);
            $bdd->flush();
        }

        return $this->render('DejaVuBundle:Default:menu.html.twig', array(
            'session' => $session
        ));
    } // GOOD
}

src/DejaVuBundle/Resources/views/Default/_alert.html.twig
<div class="close {{ class | default('') }}" id="information">{{ message }}</div>

src/DejaVuBundle/Resources/views/Default/_comment.html.twig
<div id="{{ com.comment_id }}" class="commentary">
    {% if app.session.get('user')['id'] is defined and app.session.get('user')['title_id'] < 3 and com.deleted == 0 %}
    <a class="delete_comment">{{ 'label.delete'|trans }}</a>
    <a class="update_comment">{{ 'label.modify'|trans }}</a>
    {% endif %}
    <div class="commentary_head">
        <div class="user_info">{{ 'label.by'|trans }} <a class="user_name" href="{{ path('deja_vu_user', {'name':com.pseudo_creator}) }}">
                <strong>{{ com.pseudo_creator }}</strong>
                <div class="popup_user">
                    <img class="user_avatar" src ="{{ asset('images/default_avatar.png') }}" alt="No avatar"/>
                    <div>{{ 'label.title'|trans }} : {{ com.title_name }}</div>
                    <div>{{ 'label.register'|trans }} :{{ com.registration_date | date('l j F Y') }} {{ 'label.at'|trans }} {{ com.registration_date | date('h:i') }}</div>
                    <div>{{ 'label.email'|trans }} : {{ com.email }}</div>
                </div>
            </a>{{ 'label.the'|trans }} <div class="commentary_date">{{ com.post_date | date('l j F Y') }} {{ 'label.at'|trans }} {{ com.post_date | date('h:i') }}</div>
        </div>
    </div>
    <div class="commentary_body">
        <div>
            {% if com.deleted %}
                {{ 'label.comment_deleted'|trans }}
            {% else %}
                {{ com.message }}
            {% endif %}
        </div>
    </div>
    {% if (com.editer_date) %}
        <div class="last_modification">
            <div class="user_info">{{ 'label.last_modification'|trans }}
                <a itemprop="author" itemscope="" itemtype="https://schema.org/Person" class="user_name" href="{{ path('deja_vu_user', {'name':com.pseudo_editor}) }}">
                    <strong itemprop="name">{{ com.pseudo_editor }}</strong>
                    <div class="popup_user">
                        <img class="user_avatar" src="{{ asset('images/default_avatar.png') }}" alt="No avatar">
                        <div>{{ 'label.title'|trans }} : {{ com.title_name_editor }}</div>
                        <div>{{ 'label.register'|trans }} :{{ com.registration_date_editor | date('l j F Y') }} {{ 'label.at'|trans }} {{ com.registration_date_editor | date('h:i') }}</div>
                        <div>{{ 'label.email'|trans }} : {{ com.email_editor }}</div>
                    </div>
                </a>{{ 'label.the'|trans }} {{ com.editer_date | date('l j F Y') }} {{ 'label.at'|trans }} {{ com.editer_date | date('h:i') }}.
            </div>
        </div>
        <meta itemprop="dateModified" content="{{ com.editer_date |date('y-m-d h:i:s') }}">
    {% endif %}
</div>

src/DejaVuBundle/Resources/views/Default/_news.html.twig
<div itemscope itemtype="http://schema.org/Article" class="news">
    <meta itemscope="" itemprop="mainEntityOfPage" itemtype="https://schema.org/WebPage" itemid="news/{{ news.id}}">
    <div itemprop="publisher" itemscope="" itemtype="https://schema.org/Organization">
        <div itemprop="logo" itemscope="" itemtype="https://schema.org/ImageObject">
            <meta itemprop="url" content="https://127.0.0.1/includes/icone/favicon.png">
            <meta itemprop="width" content="64">
            <meta itemprop="height" content="64">
        </div>
        <meta itemprop="name" content="{{ site_name }}">
    </div>
    <div class="news_body">
        <h2 itemprop="headline">{{ news.title }}</h2>
        <div itemprop="articleBody" class="news_text">
            {{ news.message | rawdescr }}
        </div>
        <div class="user_info">{{ 'label.by'|trans }}
            <a itemprop="author" itemscope="" itemtype="https://schema.org/Person" class="user_name" href="{{ path('deja_vu_user', {'name':news.pseudo_creator}) }}">
                <strong itemprop="name">{{ news.pseudo_creator }}</strong>
                <div class="popup_user">
                    <img class="user_avatar" src="{{ asset('images/default_avatar.png') }}" alt="No avatar">
                    <div>{{ 'label.title'|trans }} : {{ news.title_name }}</div>
                    <div>{{ 'label.register'|trans }} : {{ news.registration_date | date('l j F Y') }} {{ 'label.at'|trans }} {{ news.registration_date | date('h:i') }}</div>
                    <div>{{ 'label.email'|trans }} : {{ news.email }}</div>
                </div>
            </a>{{ 'label.the'|trans }} <div class="news_date">{{ news.post_date | date('l j F Y') }} {{ 'label.at'|trans }} {{ news.post_date | date('h:i') }}</div>
        </div>
        <meta itemprop="datePublished" content="{{ news.post_date |date('y-m-d h:i:s') }}">
        <div itemprop="image" itemscope="" itemtype="https://schema.org/ImageObject">
            <meta itemprop="url" content="https://127.0.0.1/includes/icone/favicon.png">
            <meta itemprop="width" content="64">
            <meta itemprop="height" content="64">
        </div>
        {% if id is not defined %}
            <a class="news_commentary" href="{{ path('deja_vu_viewnews', {'id':news.id, 'name':news.title|convertUrl}) }}">{{ 'label.show_commentaries'|trans }} ({{ news.nb_coms }})</a>
        {% endif %}
    </div>
    {% if (news.editer_date) %}
        <div class="last_modification">
            <div class="user_info">{{ 'label.last_modification'|trans }}
                <a itemprop="author" itemscope="" itemtype="https://schema.org/Person" class="user_name" href="{{ path('deja_vu_user', {'name':news.pseudo_editor}) }}">
                    <strong itemprop="name">{{ news.pseudo_editor }}</strong>
                    <div class="popup_user">
                        <img class="user_avatar" src="{{ asset('images/default_avatar.png') }}" alt="No avatar">
                        <div>{{ 'label.title'|trans }} : {{ news.title_name_editor }}</div>
                        <div>{{ 'label.register'|trans }} : {{ news.registration_date_editor | date('l j F Y') }} {{ 'label.at'|trans }} {{ news.registration_date_editor | date('h:i') }}</div>
                        <div>{{ 'label.email'|trans }} : {{ news.email_editor }}</div>
                    </div>
                </a>{{ 'label.the'|trans }} {{ news.editer_date | date('l j F Y') }} {{ 'label.at'|trans }} {{ news.editer_date | date('h:i') }}.
            </div>
        </div>
        <meta itemprop="dateModified" content="{{ news.editer_date |date('y-m-d h:i:s') }}">
    {% endif %}
</div>

src/DejaVuBundle/Resources/views/Default/_user.html.twig
<h3>{{ 'label.informations'|trans }}</h3>
<table class="account">
    <tr>
        <td>{{ 'label.pseudo'|trans }}</td>
        <td>{{ user.pseudo }}</td>
    </tr>
    <tr>
        <td>{{ 'label.register'|trans }}</td>
        <td>{{  user.registrationDate | date('l j F Y') }} {{ 'label.at'|trans }} {{ user.registrationDate | date('h:i') }}</td>
    </tr>
    <tr>
        <td>{{ 'label.email'|trans }}</td>
        <td>{{ user.email }}</td>
    </tr>
    <tr>
        <td>{{ 'label.title'|trans }}</td>
        <td>{{ user.title.name }}</td>
    </tr>
</table>
{% if user.id == app.session.get('user').id %}
<form id="form_edit_pwd" class="form form_fix" method="post">
    <fieldset>
        <input type="submit" value="Modifier mot de passe"/>
    </fieldset>
</form>
<div class="spinner load_form_edit_password">
    <div class="rect1"></div>
    <div class="rect2"></div>
    <div class="rect3"></div>
    <div class="rect4"></div>
    <div class="rect5"></div>
</div>
{% endif %}
<h3>{{ 'label.stats'|trans }}</h3>
<table id="account_stats" class="account">
    <tr>
        <td>{{ 'label.category'|trans }}</td>
        <td>{{ 'label.episodes'|trans }}</td>
    </tr>
    {% for stat in stats %}
    <tr>
        <td>{{ stat.name }}</td>
        <td>{{ stat.total }}</td>
    </tr>
    {% endfor %}
</table>

src/DejaVuBundle/Resources/views/Default/account.html.twig
{# src/DejaVuBundle/Resources/views/Advert/news.html.twig #}

{% extends "::layout.html.twig" %}

{% block title %}{{ 'label.account'|trans }}{% endblock %}

{% block description %}{{ 'label.account_description'|trans }}{% endblock %}

{% block javascripts %}

{% endblock %}

{% block body %}
<section>
    <h1>{{ 'label.account'|trans }}</h1>
    {{ include("DejaVuBundle:Default:_user.html.twig") }}
</section>
{% endblock %}

src/DejaVuBundle/Resources/views/Default/catalog.html.twig
{# src/DejaVuBundle/Resources/views/Advert/catalog.html.twig #}

{% extends "::layout.html.twig" %}

{% block title %}{{ 'label.catalog'|trans }}{% endblock %}

{% block description %}{{ 'label.catalog_description'|trans }}{% endblock %}

{% block javascripts %}
    {% javascripts filter="jsqueeze" output="js/filter/app.js"
    "js/filter/modernizr.js"
    "js/filter/jquery.mixitup.min.js"
    "js/filter/main.js"
    %}{% endjavascripts %}
    <script src="{{ asset("js/filter/app.js") }}"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js"></script>
    <script type="text/javascript">
        function size(){
            if($(window).width() > 1000) {
                $(function() {
                    $("img.lazy").show();
                    $("img.lazy").lazyload({
                        effect : "fadeIn"
                    });
                });
            } else {
                $("img.lazy").hide();
            }
        }
        size();
        $( window ).resize(function() {
            size();
        });
    </script>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/list.css") }}" />
    {% stylesheets filter="scssphp" output="css/list.css"
    "ui/filter/style.css"
    "ui/circle-progressbar/circle.css"
    %}{% endstylesheets %}
{% endblock %}

{% block body %}
    <main class="cd-main-content is-fixed">
        <div class="cd-tab-filter-wrapper">
            <div class="cd-tab-filter">
                <ul class="cd-filters">
                    <li class="placeholder">
                        <a data-type="all" href="{{ path('deja_vu_catalog') }}#0">{{ 'label.all'|trans }}</a>
                    </li>
                    <li class="filter"><a class="selected" href="{{ path('deja_vu_catalog') }}#0" data-type="all">{{ 'label.all'|trans }}</a></li>
                    {% for type in type_media %}
                    <li class="filter" data-filter=".{{ type.name | convertUrl }}"><a href="{{ path('deja_vu_catalog') }}#0" data-type="{{ type.name | convertUrl }}">{{ type.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {#{{ dump(series) }}#}
        <section class="cd-gallery ">
            <ul>
                {% for serie in series %}
                    {% set kinds = serie.kind | split(',') %}
                    {% set filters = serie.name | convertUrl %}
                    {% for kind in kinds %}
                        {% set filters = filters ~ " " ~ (kind | convertUrl) %}
                    {% endfor %}

                    {% if app.session.get('user')['title_id'] is defined %}
                        {% set percent = (serie.nb_episodes == 0 and serie.nb_seen == 0?100:((serie.nb_seen/serie.nb_episodes)*100)) %}
                    {% else %}
                        {% set percent = 0 %}
                    {% endif %}

                    <li class="mix {{ filters ~ (serie.is_finish?' data_finish':'') ~ (serie.is_licensed?'':' data_unlicensed') ~ (percent == 100?'':' data_seen') }}">
                        <a href="{{ path('deja_vu_viewcatalog', {'id':serie.series_id, 'name':serie.title|convertUrl}) }}">
                            <div>
                                <img alt="{{ serie.title }}" class="lazy vignette" data-original="{{ asset(serie.url_img) }}">
                                {% if serie.is_finish %}
                                <p class="finish">{{ 'label.finish'|trans }}</p>
                                {% endif %}
                                {% if serie.is_licensed %}
                                <p class="licensed">{{ serie.is_licensed }}</p>
                                {% endif %}
                            </div>
                            <div>
                                <p class="title">{{ serie.title }}{% if serie.alternativ_title %} - {{ serie.alternativ_title }} {% endif %}</p>
                                <div class="test">
                                    <div class="infos">
                                        <div class="authors_list"><div>{{ 'label.authors'|trans }} : </div>
                                            {% set authors = serie.authors|split(',') %}
                                            {% for author in authors %}
                                            <div class='authors'>{{ author }}</div>
                                            {% endfor %}
                                        </div>
                                        <div class="king_list">
                                            <div>{{ 'label.kind'|trans }} : </div>
                                            {% for kind in kinds %}
                                                <div class='king'>{{ kind }}</div>
                                            {% endfor %}
                                        {% if serie.nb_saisons != serie.nb_episodes %}
                                        <div>{{ 'label.seasons'|trans }} : {{ serie.nb_saisons }}</div>
                                        {% endif %}
                                        </div>
                                    </div>
                                    <div class="c100 p{{ percent|round }}">
                                        <span>{% if serie.nb_seen is defined %}{{ serie.nb_seen }}/{% endif %}{{ serie.nb_episodes }}</span>
                                        <div class="slice"><div class="bar"></div><div class="fill"></div></div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
            <div class="cd-fail-message">{{ 'label.no_result'|trans }}</div>
        </section>

        <div class="cd-filter">
            <div>
                <div class="cd-filter-block">
                    <div class="cd-filter-content cd-filters">
                        <input class="filter" type="search" placeholder="{{ 'label.search_sample'|trans }}">
                    </div>
                </div>
                <div class="cd-filter-block small">
                    <ul class="cd-filter-content cd-filters list">
                        <li>
                            <input class="filter" data-filter=".data_finish" type="checkbox" id="finish">
                            <label class="checkbox-label" for="finish">{{ 'label.finish'|trans }}</label>
                        </li>
                    </ul>
                </div>
                <div class="cd-filter-block small">
                    <ul class="cd-filter-content cd-filters list">
                        <li>
                            <input class="filter" data-filter=".data_unlicensed" type="checkbox" id="licenced">
                            <label class="checkbox-label" for="licenced">{{ 'label.unlicensed'|trans }}</label>
                        </li>
                    </ul>
                </div>
                {% if app.session.get('user').id is defined %}
                <div class="cd-filter-block small">
                    <ul class="cd-filter-content cd-filters list">
                        <li>
                            <input class="filter" data-filter=".data_seen" type="checkbox" id="seen">
                            <label class="checkbox-label" for="seen">{{ 'label.hide_seen'|trans }}</label>
                        </li>
                    </ul>
                </div>
                {% endif %}

                <div class="cd-filter-block huge_list">
                    <h4>{{ 'label.kind'|trans }}</h4>
                    {% for kind in kind %}
                    <ul class="cd-filter-content cd-filters list small">
                        <li>
                            <input class="filter" data-filter=".{{ kind.name | convertUrl}}" type="checkbox" id="checkbox{{ loop.index0 }}">
                            <label class="checkbox-label" for="checkbox{{ loop.index0 }}">{{ kind.name }}</label>
                        </li>
                    </ul>
                    {% endfor %}

                </div>
            </div>

            <a href="{{ path('deja_vu_catalog') }}#0" class="cd-close">{{ 'label.hide'|trans }}</a>
        </div>
        <a href="{{ path('deja_vu_catalog') }}#0" class="cd-filter-trigger ">{{ 'label.filters'|trans }}</a>
    </main>
    <div class="cd-stats-trigger"><a class="nolink">
        <span>{{ 'label.stats'|trans }}</span><img alt="" src="{{ asset('images/filter/stats_logo.png') }}" ></a>
        <div>
            {% for stat in stats %}
                {% if stat.total != stat.total_ep and stat.total != stat.total_se and stat.total_se != stat.total_ep %}
                    <p>{{ stat.name }} : {{ stat.total }}</p>
                    <ul>
                        <li>{{ 'label.seasons'|trans }} : {{ stat.total_se }}</li>
                        <li>{{ 'label.episodes'|trans }} : {{ stat.total_ep }}</li>
                    </ul>
                {% else %}
                    <p>{{ stat.name }} : {{ stat.total }}</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}
    <a id="navtop" href="#top"></a>
{% endblock %}